package com.birdex.bird.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BUSINESSMODEL".
 */
public class businessmodel {

    private String id;
    private String status;
    private String display_order;
    private String name;

    public businessmodel() {
    }

    public businessmodel(String id, String status, String display_order, String name) {
        this.id = id;
        this.status = status;
        this.display_order = display_order;
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDisplay_order() {
        return display_order;
    }

    public void setDisplay_order(String display_order) {
        this.display_order = display_order;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
