package com.birdex.bird.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY".
 */
public class city {

    private Long id;
    private String Area;
    private String AreaID;
    private String AreaName;
    private String ParentID;

    public city() {
    }

    public city(Long id) {
        this.id = id;
    }

    public city(Long id, String Area, String AreaID, String AreaName, String ParentID) {
        this.id = id;
        this.Area = Area;
        this.AreaID = AreaID;
        this.AreaName = AreaName;
        this.ParentID = ParentID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getArea() {
        return Area;
    }

    public void setArea(String Area) {
        this.Area = Area;
    }

    public String getAreaID() {
        return AreaID;
    }

    public void setAreaID(String AreaID) {
        this.AreaID = AreaID;
    }

    public String getAreaName() {
        return AreaName;
    }

    public void setAreaName(String AreaName) {
        this.AreaName = AreaName;
    }

    public String getParentID() {
        return ParentID;
    }

    public void setParentID(String ParentID) {
        this.ParentID = ParentID;
    }

}
