package com.birdex.bird.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.birdex.bird.greendao.NotifiMsg;

import com.birdex.bird.greendao.NotifiMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notifiMsgDaoConfig;

    private final NotifiMsgDao notifiMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notifiMsgDaoConfig = daoConfigMap.get(NotifiMsgDao.class).clone();
        notifiMsgDaoConfig.initIdentityScope(type);

        notifiMsgDao = new NotifiMsgDao(notifiMsgDaoConfig, this);

        registerDao(NotifiMsg.class, notifiMsgDao);
    }
    
    public void clear() {
        notifiMsgDaoConfig.getIdentityScope().clear();
    }

    public NotifiMsgDao getNotifiMsgDao() {
        return notifiMsgDao;
    }

}
