package com.birdex.bird.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.birdex.bird.greendao.NotifiMsg;
import com.birdex.bird.greendao.warehouse;
import com.birdex.bird.greendao.market;
import com.birdex.bird.greendao.priceUnit;
import com.birdex.bird.greendao.servicetype;
import com.birdex.bird.greendao.box;
import com.birdex.bird.greendao.qgmodel;
import com.birdex.bird.greendao.tape;
import com.birdex.bird.greendao.businessmodel;
import com.birdex.bird.greendao.ticket;
import com.birdex.bird.greendao.city;

import com.birdex.bird.greendao.NotifiMsgDao;
import com.birdex.bird.greendao.warehouseDao;
import com.birdex.bird.greendao.marketDao;
import com.birdex.bird.greendao.priceUnitDao;
import com.birdex.bird.greendao.servicetypeDao;
import com.birdex.bird.greendao.boxDao;
import com.birdex.bird.greendao.qgmodelDao;
import com.birdex.bird.greendao.tapeDao;
import com.birdex.bird.greendao.businessmodelDao;
import com.birdex.bird.greendao.ticketDao;
import com.birdex.bird.greendao.cityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notifiMsgDaoConfig;
    private final DaoConfig warehouseDaoConfig;
    private final DaoConfig marketDaoConfig;
    private final DaoConfig priceUnitDaoConfig;
    private final DaoConfig servicetypeDaoConfig;
    private final DaoConfig boxDaoConfig;
    private final DaoConfig qgmodelDaoConfig;
    private final DaoConfig tapeDaoConfig;
    private final DaoConfig businessmodelDaoConfig;
    private final DaoConfig ticketDaoConfig;
    private final DaoConfig cityDaoConfig;

    private final NotifiMsgDao notifiMsgDao;
    private final warehouseDao warehouseDao;
    private final marketDao marketDao;
    private final priceUnitDao priceUnitDao;
    private final servicetypeDao servicetypeDao;
    private final boxDao boxDao;
    private final qgmodelDao qgmodelDao;
    private final tapeDao tapeDao;
    private final businessmodelDao businessmodelDao;
    private final ticketDao ticketDao;
    private final cityDao cityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notifiMsgDaoConfig = daoConfigMap.get(NotifiMsgDao.class).clone();
        notifiMsgDaoConfig.initIdentityScope(type);

        warehouseDaoConfig = daoConfigMap.get(warehouseDao.class).clone();
        warehouseDaoConfig.initIdentityScope(type);

        marketDaoConfig = daoConfigMap.get(marketDao.class).clone();
        marketDaoConfig.initIdentityScope(type);

        priceUnitDaoConfig = daoConfigMap.get(priceUnitDao.class).clone();
        priceUnitDaoConfig.initIdentityScope(type);

        servicetypeDaoConfig = daoConfigMap.get(servicetypeDao.class).clone();
        servicetypeDaoConfig.initIdentityScope(type);

        boxDaoConfig = daoConfigMap.get(boxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        qgmodelDaoConfig = daoConfigMap.get(qgmodelDao.class).clone();
        qgmodelDaoConfig.initIdentityScope(type);

        tapeDaoConfig = daoConfigMap.get(tapeDao.class).clone();
        tapeDaoConfig.initIdentityScope(type);

        businessmodelDaoConfig = daoConfigMap.get(businessmodelDao.class).clone();
        businessmodelDaoConfig.initIdentityScope(type);

        ticketDaoConfig = daoConfigMap.get(ticketDao.class).clone();
        ticketDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(cityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        notifiMsgDao = new NotifiMsgDao(notifiMsgDaoConfig, this);
        warehouseDao = new warehouseDao(warehouseDaoConfig, this);
        marketDao = new marketDao(marketDaoConfig, this);
        priceUnitDao = new priceUnitDao(priceUnitDaoConfig, this);
        servicetypeDao = new servicetypeDao(servicetypeDaoConfig, this);
        boxDao = new boxDao(boxDaoConfig, this);
        qgmodelDao = new qgmodelDao(qgmodelDaoConfig, this);
        tapeDao = new tapeDao(tapeDaoConfig, this);
        businessmodelDao = new businessmodelDao(businessmodelDaoConfig, this);
        ticketDao = new ticketDao(ticketDaoConfig, this);
        cityDao = new cityDao(cityDaoConfig, this);

        registerDao(NotifiMsg.class, notifiMsgDao);
        registerDao(warehouse.class, warehouseDao);
        registerDao(market.class, marketDao);
        registerDao(priceUnit.class, priceUnitDao);
        registerDao(servicetype.class, servicetypeDao);
        registerDao(box.class, boxDao);
        registerDao(qgmodel.class, qgmodelDao);
        registerDao(tape.class, tapeDao);
        registerDao(businessmodel.class, businessmodelDao);
        registerDao(ticket.class, ticketDao);
        registerDao(city.class, cityDao);
    }
    
    public void clear() {
        notifiMsgDaoConfig.getIdentityScope().clear();
        warehouseDaoConfig.getIdentityScope().clear();
        marketDaoConfig.getIdentityScope().clear();
        priceUnitDaoConfig.getIdentityScope().clear();
        servicetypeDaoConfig.getIdentityScope().clear();
        boxDaoConfig.getIdentityScope().clear();
        qgmodelDaoConfig.getIdentityScope().clear();
        tapeDaoConfig.getIdentityScope().clear();
        businessmodelDaoConfig.getIdentityScope().clear();
        ticketDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
    }

    public NotifiMsgDao getNotifiMsgDao() {
        return notifiMsgDao;
    }

    public warehouseDao getWarehouseDao() {
        return warehouseDao;
    }

    public marketDao getMarketDao() {
        return marketDao;
    }

    public priceUnitDao getPriceUnitDao() {
        return priceUnitDao;
    }

    public servicetypeDao getServicetypeDao() {
        return servicetypeDao;
    }

    public boxDao getBoxDao() {
        return boxDao;
    }

    public qgmodelDao getQgmodelDao() {
        return qgmodelDao;
    }

    public tapeDao getTapeDao() {
        return tapeDao;
    }

    public businessmodelDao getBusinessmodelDao() {
        return businessmodelDao;
    }

    public ticketDao getTicketDao() {
        return ticketDao;
    }

    public cityDao getCityDao() {
        return cityDao;
    }

}
