package com.birdex.bird.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTIFI_MSG".
 */
public class NotifiMsg {

    private Long id;
    /** Not-null value. */
    private String title;
    private String msgtext;
    private Boolean isread;
    private String msgdate;
    private String typeid;
    private String params;

    public NotifiMsg() {
    }

    public NotifiMsg(Long id) {
        this.id = id;
    }

    public NotifiMsg(Long id, String title, String msgtext, Boolean isread, String msgdate, String typeid, String params) {
        this.id = id;
        this.title = title;
        this.msgtext = msgtext;
        this.isread = isread;
        this.msgdate = msgdate;
        this.typeid = typeid;
        this.params = params;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getMsgtext() {
        return msgtext;
    }

    public void setMsgtext(String msgtext) {
        this.msgtext = msgtext;
    }

    public Boolean getIsread() {
        return isread;
    }

    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    public String getMsgdate() {
        return msgdate;
    }

    public void setMsgdate(String msgdate) {
        this.msgdate = msgdate;
    }

    public String getTypeid() {
        return typeid;
    }

    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

}
