package com.birdex.bird.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QGMODEL".
 */
public class qgmodel {

    private String id;
    private String status;
    private String description;
    private String display_order;
    private String name;

    public qgmodel() {
    }

    public qgmodel(String id, String status, String description, String display_order, String name) {
        this.id = id;
        this.status = status;
        this.description = description;
        this.display_order = display_order;
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDisplay_order() {
        return display_order;
    }

    public void setDisplay_order(String display_order) {
        this.display_order = display_order;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
