package com.birdex.bird.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SERVICETYPE".
 */
public class servicetype {

    private String key;
    private String id;
    private String is_show;
    private String name;

    public servicetype() {
    }

    public servicetype(String key, String id, String is_show, String name) {
        this.key = key;
        this.id = id;
        this.is_show = is_show;
        this.name = name;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIs_show() {
        return is_show;
    }

    public void setIs_show(String is_show) {
        this.is_show = is_show;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
