package com.birdex.bird.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WAREHOUSE".
 */
public class warehouse {

    private String sort;
    private String iconUrl;
    private String tel;
    private String postCode;
    private String warehouseId;
    private String city;
    private String country;
    private String id;
    private String name;
    private String addressInfo;
    private String province;
    private String district;
    private String isShow;
    private String mapUrl;

    public warehouse() {
    }

    public warehouse(String sort, String iconUrl, String tel, String postCode, String warehouseId, String city, String country, String id, String name, String addressInfo, String province, String district, String isShow, String mapUrl) {
        this.sort = sort;
        this.iconUrl = iconUrl;
        this.tel = tel;
        this.postCode = postCode;
        this.warehouseId = warehouseId;
        this.city = city;
        this.country = country;
        this.id = id;
        this.name = name;
        this.addressInfo = addressInfo;
        this.province = province;
        this.district = district;
        this.isShow = isShow;
        this.mapUrl = mapUrl;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getPostCode() {
        return postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    public String getWarehouseId() {
        return warehouseId;
    }

    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddressInfo() {
        return addressInfo;
    }

    public void setAddressInfo(String addressInfo) {
        this.addressInfo = addressInfo;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getIsShow() {
        return isShow;
    }

    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    public String getMapUrl() {
        return mapUrl;
    }

    public void setMapUrl(String mapUrl) {
        this.mapUrl = mapUrl;
    }

}
